CREATE TABLE recovery_password_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp without time zone,
    token character varying(255) COLLATE pg_catalog."default",
    user_email character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT recovery_password_token_pkey PRIMARY KEY (id),
    CONSTRAINT fk1ap0jm9ifhnpgvpq4a5xa5yht FOREIGN KEY (user_email)
        REFERENCES public.users (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
