CREATE TABLE users
(
    email character varying(255) NOT NULL,
    enabled boolean,
    last_name character varying(255),
    name character varying(255),
    password character varying(255),
    user_role integer,
    CONSTRAINT users_pkey PRIMARY KEY (email)
);

CREATE TABLE contact
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    last_name character varying(255),
    name character varying(255),
    type integer,
    user_email character varying(255),
    CONSTRAINT contact_pkey PRIMARY KEY (id),
    CONSTRAINT fkf6cg7evr3j74ohnmfhogfoc1q FOREIGN KEY (user_email)
        REFERENCES users (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE address
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address character varying(255),
    city character varying(255),
    country character varying(255),
    type integer,
    zip_code integer NOT NULL,
    contact_id integer,
    CONSTRAINT address_pkey PRIMARY KEY (id),
    CONSTRAINT fk660ac8r9vntokuyh6agtj8pkh FOREIGN KEY (contact_id)
        REFERENCES contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE confirmation_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp without time zone,
    token character varying(255),
    user_email character varying(255),
    CONSTRAINT confirmation_token_pkey PRIMARY KEY (id),
    CONSTRAINT fk2e7il3phhs49qcwdlqmaome91 FOREIGN KEY (user_email)
        REFERENCES users (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE email
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    type integer,
    contact_id integer,
    CONSTRAINT email_pkey PRIMARY KEY (id),
    CONSTRAINT fk85pasi49am6xyaxoph3i9rvl4 FOREIGN KEY (contact_id)
        REFERENCES contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE phone
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code_country integer,
    "number" character varying(255),
    type integer,
    contact_id integer,
    CONSTRAINT phone_pkey PRIMARY KEY (id),
    CONSTRAINT fkcpsuk117j8h3rplllpvtgs38a FOREIGN KEY (contact_id)
        REFERENCES contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
