ALTER TABLE users
RENAME COLUMN enabled TO is_confirmed;

ALTER TABLE contact
DROP CONSTRAINT fkf6cg7evr3j74ohnmfhogfoc1q,
ADD CONSTRAINT fkf6cg7evr3j74ohnmfhogfoc1q FOREIGN KEY (user_email)
        REFERENCES users (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;

CREATE TABLE recovery_password_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date timestamp without time zone,
    token character varying(255),
    user_email character varying(255),
    CONSTRAINT recovery_password_token_pkey PRIMARY KEY (id),
    CONSTRAINT fk1ap0jm9ifhnpgvpq4a5xa5yht FOREIGN KEY (user_email)
        REFERENCES users (email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
